src/Dropdown/Dropdown.jsx
This was replacing `selectedInd` when it was equal to `0`. Instead, check if it is `undefined` and then replace
=> Only replace selectedInd if it's undefined (was replacing when 0 too

src/AvailabilityGrid/AvailabilityGrid.jsx
- Don't use fill because Safari doesn't support it.
=> Fix availability grid on Safari

src/AppBar/linkSet.es6
Having a reference to `global.__env.user` in `linkSet` creates a dependency whenever you import something from the root of the `thinkful-ui`. This makes that value optional.
=> Make __env optional for linkSet

src/AppBar/app-bar.less, src/DatePicker/DatePicker.jsx, src/DatePicker/datepicker.less
Now supports showing "Today" and month name together.
Allows clicking on dates in the next / previous month even if you don't navigate to them. (e.g. the first few days of the next month are now clickable)
Fixes https://github.com/Thinkful/Thinkful/issues/171
=> Change datepicker ux, show 'Today' w/ month name

src/ProxyPathUtils.es6, src/index.es6
The slug is config.app.slug from the JavaScript __env.  For reverse-proxied apps formerly known as
`appname.thinkful.com` this will be `/appname`
=> Add pathWithSlug/pathWithoutSlug utils for reverse proxied apps

package.json, src/OpenSessionOverview/OpenSessionOverview.jsx, src/models/OpenSessionsModel.es6
Goes along with https://github.com/Thinkful/cuckoo/pull/309 -- checks if a user is active in the `OpenSessionOverview` component before allowing them to RSVP.  Note this only applies to QA sessions (can't RSVP for a workshop from that overview screen)
=> check if user is active in overview

package.json, src/analytics/actions.es6
Fixes the error thrown for some secret signup enrollments when no "from" address is passed to AnalyticsAPI.alias. 
This addresses https://github.com/Thinkful/Thinkful/issues/154
=> Check for undefined "to" and "from" args

client/DemoPage.jsx, client/styles/demo.less, package.json, src/OpenSessionOverview/OpenSessionOverview.jsx, src/Tag/Tag.jsx, src/TopicPicker/TopicPicker.jsx, src/TopicPicker/index.es6, src/TopicPicker/topic-picker.less, src/index.es6
Note:
* This required small changes to `Tag` component
* Fixes a bug in `_filterTopicList` whereby inputting a topic like `C++` when `availableTopics` was passed in caused an error.
* Makes `minTopicLength` configurable, but defaults to 0.
* Has new requirements so running locally will need to ./script/install
Also, shortly after this is released, both Raven and Cuckoo will be updated to comply with updated `Tag` props, and to use `TopicPicker` from UI.
=> TopicPicker Relocates to UI

package.json, src/TopicPicker/TopicPicker.jsx
topic picker was failing in some apps with error
discussed here: https://gist.github.com/jimfb/4faa6cbfb1ef476bd105
after numerous dead ends, turned out that the refs inside
TopicPicker were causing this issue. Easily addressed by getting
rid of refs.
=> get rid of use of refs and use onKeyDown

package.json, webpack.defaults.js
This appears to solve the dreaded invariant violation error we've been getting when using components with `.refs` from thinkful-ui (discussed [here](https://gist.github.com/jimfb/4faa6cbfb1ef476bd105)).
=> Alias react

package.json, src/Sidebar/Layout.jsx, src/SocialShare/SocialShare.jsx, src/SocialShare/index.es6, src/SocialShare/social-share.less, src/index.es6
Adds a component that you can use to automagically create a social share button for twitter, linkedin or facebook.  It's very un-opinionated on what the element should look like because we may want buttons vs icons at various spots throughout the site.  Component takes a `url` (facebook and linkedin) or `content` (twitter) to share 
usage:
```
<SocialShare type="twitter" content="A tweet">
<Icon name="twitter"/>
</SocialShare>
```
=> add social share wrapper

package.json, src/analytics/actions.es6
I don't believe we have any code in the wild that actually hits this, but I noticed it and it should be fixed anyways.
=> Small fix for edge case in identifying with traits as first parameter and no ID.

package.json, src/analytics/actions.es6
- Instead of `__env` and `appInfo` being consts, source them from the most up-to-date versions.
- Only use directly imported lodash functions.
- Tested with Pelican and it worked, but review closely since the changes are very spread out.
=> Changes to allow for getting most up-to-date __env.

package.json, src/AppBar/Navigation.jsx
Tf-Guest signins are "Authenticated" so they have a `window.__env.user`, meaning AppBar will try to show the logged-in version.  Luckily `role !== 'guest'` will discriminate.
=> Tf-Guest signins see unauthed version of navbar

package.json, src/Dropdown/Dropdown.jsx
The `Dropdown` component previously accepted an array of objects for data, along with a `selectedInd` for the selected item ala:
```
data = [
{'value': 1, 'displayName': 'foo'},
{'value': 2, 'displayName': 'bar'}];
```
This PR allows it to accept just a simple array of strings and assumes that those strings should be both the value and display name for each item.  It also now accepts a `value` prop, which will replace `selectedInd` so that you don't need to search for the index outside of the component
=> allow dropdown to accept simple array

package.json, src/AppBar/notifications/NotificationActions.es6
[faye 1.2.0](https://github.com/faye/faye/releases/tag/1.2.0) appears to break semver (though unsure how). The upgrade from `getstream` 2.x to 3.x looks like an in-place upgrade for us.
We use the following methods:
- `stream.connect` (option with api key and app key)
- `client.feed`
- `feed.get` (with options `limit`, `mark_seen`, and `mark_read`)
all of which remain the same between 2.x and 3.x
`getstream` 3.4 pins faye at 1.2.0
[:metal:🎶](https://www.youtube.com/watch?v=LYU-8IFcDPw) I can't faye...the way I did before! Don't break semver on me! I won't be ignored! [🎶:metal:](https://www.youtube.com/watch?v=LYU-8IFcDPw)
=> Update getstream to 3.4

src/OpenSessionOverview/OpenSessionOverview.jsx
Per Ariana's request, we're going back to displaying a unique description for each qa session.
PR 1/2
=> display descriptions for qa sessions on overview screen

package.json, src/DatePicker/DatePicker.jsx
Some improvements to the `DatePicker` -
- defaults to "today" as the active day if none passed
- dropdown closes when you click somewhere else on the screen
- supports displaying a placeholder value in the dropdown until a date is picked (such as "Select a date", etc)
- use thinkful ui `Icon` component
=> date picker improvements

client/DemoPage.jsx, package.json, src/Dropdown/Dropdown.jsx, src/Dropdown/dropdown.less
Improves usability / accessibility of the dropdown component.
Retains existing API for the component, adds label-friendly `id` option.
JP's original edition: https://github.com/Thinkful/ui/pull/315
=> HTML-ify the Dropdown component

package.json, src/analytics/actions.es6
Fix on .identify
---------------
Fix on .identify stops us from sending an email trait to an anonymous
profile. This causes duplicates in both mixpanel and heap, as a
profile whose id is still a UUID gets an email. This doesn't make sense
since we could technically create several of these "unaliased" profiles
for the same person, and wouldn't be able to merge them at any point.
The expected outcome is that identify will be called with the email,
forcing the anonymous profile to be dettached in Mixpanel (we lose
history) and forcing a creation of a profile with that email.
Heap should merge the anonymous history instead of "orphaning" it.
Fix on .alias
------------
Fix on .alias prevents the AnalyticsAPI object from aliasing users
already identified as profile with an email, to a different …
=> fix(analytics): stop mixpanel dups

package.json, src/OpenSessionOverview/OpenSessionOverview.jsx
Fixes a typo that was breaking open-sessions page:
Since I was editing `ui` I made another improvement to my previous changes
=> Fix typo and add link to student activity

package-lock.json, package.json, src/Gravatar.jsx, src/Icon.jsx, src/OneClickCopy/OneClickCopy.jsx, src/OpenSessionOverview/OpenSessionOverview.jsx, src/SearchBar/SearchActions.js, src/SearchBar/SearchBar.jsx, src/Sidebar/Layout.jsx, src/Sidebar/Menu.jsx, src/Sidebar/MenuItem.jsx, src/Sidebar/index.js, src/SocialShare/SocialShare.jsx, src/Tag/Tag.jsx, src/TopicPicker/TopicPicker.jsx, src/TrackedLink/TrackedLink.jsx
- Start migrating to the `prop-types` package instead of `React.PropTypes`
- Some linting of files
No functional changes
`PropTypes` were pulled out of the react package and removed in React 16, so before upgrading, this needs to be changed
As far as linting goes, some components are getting changed to the lighter functional style and `stage-0` features are being replaced. We shouldn't be using these features, because they're not guaranteed to be a part of future releases
=> Prop types 1

package-lock.json, package.json, src/AppBar/notifications/NotificationActions.jsx
We're reaching our API limit with stream, which we use for the nav bar notifications.  Design system users don't get those notifications, we should suppress any calls to the API for them
=> supress call to stream API for DS users

less/modules/app-bar.less, src/AppBar/DesktopMenuToggle.jsx, src/AppBar/MobileMenuToggle.jsx
phab/video: https://phabricator.bloc.io/T12240#291090
set `visibility:hidden` on the nav list unless explicitly shown, so it doesn't show up in the tab order. also, add some `aria-label`s on the elements that toggle the nav list, so screen readers announce them
=> [T12240] menu bar tab accessibility improvements

package.json, src/AppBar/currentEnrollment.js
Funny thing!
This call is causing A BUNCH of 404 requests to pysplash: https://logentries.com/app/f5d9d6aa#/search/log/9fd341ea?log_q=where(status%3D404)&last=Last%2020%20Minutes
Funnier thing!
For 404s, pysplash makes a request to Pelican for the HTML of its 404 page.
Funniest thing!
This combination makes the 404 "endpoint" the 5th most time-consuming transaction in our API!
=> dont make a request if the contactId is undefined

package.json, src/AppBar/AppBar.jsx
Bump version, add new feature flag to concierge as well as check for prep enrollment
This is to enable testing cards such as https://phabricator.bloc.io/T13311 and the concierge stories that follow it.
=> T13311 Add concierge prep feature flag and check for prep enrollment.

less/modules/app-bar.less, src/AppBar/AppBar.jsx, src/AppBar/ConciergeModal.jsx, src/AppBar/ConciergeOption.jsx
With contact link:
Original unchanged:
=> add prep contact link to concierge modal

package.json, src/AppBar/currentEnrollment.js
This is needed because non-Seagull apps inject a `user` object that uses snake_case, not camelCase. 
See https://phabricator.bloc.io/T13562
=> T13562 Use snake case fallback when fetching enrollment.
