package.json, webpack.defaults.js
... and allow raw html in markdown files
=> Use remarkable-loader for loading markdown

package.json
=> Master < Develop

src/AppBar/linkSet.es6
=> Move 'My Students' into left nav for mentors/admins

src/Dropdown.jsx, src/dropdown.less, src/index.es6, webpack.hotload.js
Adds shared dropdown element to thinkful ui.
=> Add shared dropdown element

src/AppBar/Navigation.jsx, src/AppBar/app-bar.less
Fixes #15, could use a little CSS animation tuning (disappears instantly, not exactly sure why, but I may have been editing peacock's `nav.less` accidentally)
=> Hide dropdown.

src/AppBar/Navigation.jsx, src/AppBar/linkSet.es6
=> Open external link in new tab

src/AvailabilityGrid/AvailabilityGrid.jsx, src/AvailabilityGrid/availability_grid.less
Availability component to end all availability components. First implemented in Robin, this component had the robin-specific API aspects pulled out and moved into a wrapper. This is the display-only part of the component.
After this request is merged, this component will then be imported by Robin, and then by Ostrich and Tailorbird and anyone else who needs an availability chooser. 
Next steps, after implementing in projects, will be to update the styling to match the new design mockup.
=> Availability ui component

src/AvailabilityGrid/AvailabilityGrid.jsx, src/AvailabilityGrid/availability_grid.less, src/AvailabilityGrid/index.es6, src/index.es6
Small changes to make AvailabilityGrid actually importable, and some style changes to closer fit mockup.
=> Fixes and style changes when integrating into robin.

package.json, src/AvailabilityGrid/AvailabilityGrid.jsx
for DatePicker and AvailabilityGrid to package.json.
=> add missing dependencies

src/AppBar/Navigation.jsx
As requested [here](https://github.com/Thinkful/pelican/issues/939)
=> thinkful logo in nav bar links to www home

src/AppBar/Navigation.jsx, src/AppBar/linkSet.es6
=> Link T to Home.

src/DatePicker/DatePicker.es6, src/DatePicker/datepicker.less, src/Dropdown/Dropdown.jsx, src/Dropdown/dropdown.less
@evanrs  please take a look when you have a minute. Minor changes to style, default props, etc in date picker and dropdown
=> Update date picker and dropdown elements following work in roadrunner

client/DemoPage.jsx, client/HomePage.jsx, client/StaticModalPage.jsx, client/routes.jsx, src/Modal/Modal.jsx, src/Modal/index.es6, src/Modal/modal.less, src/index.es6
Simple modal that includes an X and a curtain to close it. Mounts in-place (so it has to be in a non-hidden, non-transformed div).
The demo includes a button in the center to close the modal but this is totally optional - the host application would chose what to put in the modal.
Should I add an optional width= prop?
=> Modal window

client/DemoPage.jsx, src/Loader/Loader.jsx, src/Loader/index.es6, src/Loader/loader.less, src/index.es6
Looks like this:
Any ideas for arguments? Does it need a "height" option or something?
=> Add Loader widget

src/AppBar/NavLink.jsx, src/AppBar/Navigation.jsx, src/AppBar/app-bar.less, src/AppBar/linkSet.es6
=> Feature/logged out nav 2.0

package.json, src/AppBar/Navigation.jsx, src/AppBar/app-bar.less
=> Add React to Learn dropdown, put CP first, add ⌄ next to Learn

src/AvailabilityGrid/AvailabilityGrid.jsx, src/AvailabilityGrid/availability_grid.less
Half-fixes https://github.com/Thinkful/Thinkful/issues/119
//cc @tholex @paulaborowska
=> Make selected times more visible

src/AppBar/Navigation.jsx, src/AppBar/app-bar.less
=> Changes "Learn" to "Courses"

src/AppBar/linkSet.es6
Requires https://github.com/Thinkful/tfcommons/pull/239/files
=> Naming consistency: "Office hours" -> "Workshops"

package.json, src/FourOhFour/FourOhFour.jsx
Otherwise send folks to projects.
https://github.com/Thinkful/Thinkful/issues/126
=> Only use history if history exists

package.json, src/Footer/Footer.jsx, src/Footer/footer.less
Adds the timezone optionally to the footer component
=> add timezone to footer

package.json, src/AppBar/NavLink.jsx, src/AppBar/search/SearchBar.jsx, src/AppBar/search/search-bar.less
Adds an underlay to the search bar that fades from white to transparent. Clicking away from the search bar closes search
=> add underlay and click away event

package.json, src/SearchBar/SearchBar.jsx, src/SearchBar/search-bar.less, src/Tag/tag.less
fixes parts of https://github.com/Thinkful/raven/issues/322
=> add hover state to tags, "browse by topic" to search screen

package.json, src/OpenSessionOverview/OpenSessionOverview.jsx, src/OpenSessionOverview/open-session-overview.less
fixes https://github.com/Thinkful/Thinkful/issues/172
=> fix handling of links in open session overview component

client/index.es6, package.json, src/AvailabilityGrid/AvailabilityGrid.jsx, src/Loader/Loader.jsx, src/NotificationView/NotificationView.jsx, src/SearchBar/SearchBar.jsx
- Upgrades `react`, `react-router`, and `react-demo`
- Adds `react-dom` library
- Makes changes required for update, [specified here](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html)
=> Update to React 0.14

package.json, src/AppBar/Navigation.jsx
needs to follow https://github.com/Thinkful/pysplash/pull/2345
=> use avatar endpoint for app bar image

demo/__env.json
=> add api config to demo page

package.json, src/Dropdown/Dropdown.jsx
=> Improve close targeting

package.json, src/AppBar/Navigation.jsx
=> remove workshops from nav

package.json, src/AppBar/Navigation.jsx
Should be released at same time as https://github.com/Thinkful/pelican/pull/1830
=> Update positioning in nav to remove "full time" and "part time"

src/AvatarUploader/AvatarUploader.jsx, src/AvatarUploader/avatar-uploader.less, src/AvatarUploader/index.es6, src/index.es6
=> add AvatarUploader to thinkful-ui

src/AvailabilityGrid/availability_grid.less
to match paula's most recent design:
=> update availability grid styles

package.json, src/AvailabilityGrid/AvailabilityGrid.jsx
Add methods to AvailabilityGrid to get the number of days/hours that are selected
=> add funtions to get number of days/hours selected

src/AppBar/NavLink.jsx, src/AppBar/Navigation.jsx, src/AppBar/app-bar.less, src/AppBar/linkSet.es6
=> disable workshops link in onboarding

package.json, src/AppBar/linkSet.es6
As part of TFL clean up we want "Q&A sessions" in nav not "Workshops"
I also just added some comments about which view is which...let me know if you think I should remove
=> show Q&A sessions in nav not workshops

client/DemoPage.jsx, package.json, src/Loader/Loader.jsx, src/Loader/loader.less
similar to http://codepen.io/tholex/pen/GZvYGm but a little smaller
=> Material-style loader instead of 'loading...'

src/Dropdown/Dropdown.jsx
allow falsy items to be values in dropdown
=> allow null values in dropdown

demo/__env.json, src/AppBar/linkSet.es6
=> show goals to PT CP students

src/OpenSessionOverview/OpenSessionOverview.jsx
Result, for info sessions / admins only:
@jcudmore
=> link to rsvp list in adminium for info sessions

package.json, src/analytics/actions.es6
If this doesn't work, we're hopeless.
=> Block segment from loading at all if user is impersonating.

src/NotificationView/notifications.less
fixes https://github.com/Thinkful/Thinkful/issues/647
=> add overflow: scroll

src/AppBar/LoggedOutNav.jsx, src/AppBar/Navigation.jsx, src/AppBar/app-bar.less
The line count may look scary but it's basically a copy + paste from pelican with reactified interactions for dropdowns, etc.
=> update logged out nav to match pelican

package.json, src/analytics/actions.es6
Somewhere emails are dupping with caps profiles...trying to pin down where but no getting the issue locally
Ex https://github.com/Thinkful/Thinkful/issues/849
=> make emails lowercase

package.json, src/AvailabilityGrid/AvailabilityGrid.jsx, src/Footer/Footer.jsx
part 1 of fixing https://github.com/Thinkful/Thinkful/issues/879
=> set default props for availability grid, add keys

client/DemoPage.jsx, src/Dropdown/Dropdown.jsx, src/Dropdown/dropdown.less
Merging into a local branch so I can fix merge conflicts & test.
=> Dropdown html

src/analytics/actions.es6
No need to tip-toe around identifying and aliasing anymore. Go ham.
=> feat(analytics): undo mixpanel workarounds

package.json, src/AvailabilityGrid/availability_grid.less
O_o surprised it's made of hardcoded px but no time to re-do the layout
=> Fix for no fonts / avenir

src/OpenSessionOverview/OpenSessionOverview.jsx, src/OpenSessionOverview/open-session-overview.less
Closes: https://trello.com/c/F0xoRmrm/531-show-rsvpd-people-for-qa-sessions
=> Add participant list to qa session overview

package.json, src/AppBar/CourseLink.jsx, src/AppBar/LoggedOutNav.jsx, src/AppBar/NavLink.jsx
Old PR that I just discovered was still open 
These params are not particularly helpful for analytics and not good for SEO in general
=> remove redundant nav analytics that are parameters

src/OpenSessionOverview/OpenSessionOverview.jsx
Solves: https://bloopers.thinkful.com/thinkful/pysplash/issues/267/events/latest/
Long time without using React so 🙏, double check haha
=> disable rsvp button on click

package.json, src/AppBar/linkSet.es6
"Goals" moving to dashboard app nav via https://github.com/Thinkful/peacock/pull/799
=> remove goals from nav

src/DatePicker/DatePicker.jsx, src/Dropdown/Dropdown.jsx
Part 4 of `prop-types` palooza
=> Prop types 4

src/DatePicker/DatePicker.jsx, src/Dropdown/Dropdown.jsx, src/Footer/Footer.jsx, src/FourOhFour/FourOhFour.jsx, src/Loader/Loader.jsx, src/Modal/Modal.jsx, src/NotificationView/VotingBar.jsx
Third part of the prop-type-palooza
=> Prop types 3

src/DatePicker/DatePicker.jsx, src/Dropdown/Dropdown.jsx, src/Footer/Footer.jsx, src/FourOhFour/FourOhFour.jsx, src/Loader/Loader.jsx, src/Modal/Modal.jsx, src/NotificationView/NotificationItem.jsx, src/NotificationView/NotificationView.jsx, src/NotificationView/VotingBar.jsx
=> Lint/add PropTypes to NotificationView

src/AppBar/CourseLink.jsx, src/AppBar/LoggedOutNav.jsx, src/AppBar/NavLink.jsx, src/AppBar/Navigation.jsx, src/AppBar/SearchLink.jsx, src/AppBar/index.js, src/AppBar/index.jsx, src/AppBar/notifications/Notifications.jsx
`PropTypes` part 6: The Final Palooz
=> Prop types 6

.npmignore, package.json, src/AppBar/LoggedOutNav.jsx, src/AppBar/Navigation.jsx, src/AppBar/WhiteTLogo.jsx, src/AppBar/linkSet.js, src/AppBar/notifications/Notifications.jsx, src/AvailabilityGrid/AvailabilityGrid.jsx, src/Gravatar.jsx, src/NotificationView/NotificationView.jsx, stories/env.js, stories/index.stories.js
- Fix various issues with updated navbar
- turn linkSet into a function that takes a config and user object and only falls back to a global if available
=> Navbar fixes

less/modules/notifications.less, package.json, src/AppBar/FaqLink.js, src/AppBar/Navigation.jsx
=> add FAQ link to navbar

.babelrc, README.md, less/modules/app-bar.less, package-lock.json, package.json, src/AppBar/Navigation.jsx, src/index.js, src/styleguide/index.js
=> style dropdown menu

less/modules/notifications.less, src/AppBar/AppBar.jsx, src/NotificationView/NotificationItem.jsx, src/NotificationView/NotificationView.jsx
=> style in-app notifications

less/modules/app-bar.less, less/modules/notifications.less, src/AppBar/AppBar.jsx, src/AppBar/DesktopMenuToggle.jsx, src/AppBar/MenuList.jsx, src/AppBar/MobileMenuToggle.jsx, src/AppBar/NavLink.jsx, src/AppBar/UnauthedAppBar.jsx, src/AppBar/WhiteTLogo.jsx, src/AppBar/linkSet.js, src/NotificationView/NotificationItem.jsx, src/NotificationView/NotificationView.jsx, src/NotificationView/VotingBar.jsx
=> prefix class names, add UnauthedAppBar

less/modules/notifications.less, package-lock.json, package.json, src/NotificationView/NotificationItem.jsx, src/NotificationView/NotificationView.jsx, src/SvgIcon/Icons/Bell.jsx, src/SvgIcon/Icons/Book.jsx, src/SvgIcon/Icons/Close.jsx, src/SvgIcon/SvgIcon.jsx
=> add nav icons

package-lock.json, package.json, src/AppBar/DesktopMenuToggle.jsx
An empty `href` is getting added to this anchor tag on peacock for whatever reason, which is causing the page to refresh when clicked.  Adding an explicit href here _should_ fix the problem 🤞 
For https://phabricator.bloc.io/T10781
=> add explicit href to app nav toggle

package.json, src/AvailabilityGrid/AvailabilityGrid.jsx, src/Footer/Footer.jsx, src/NotificationView/NotificationView.jsx
This was causing issues when testing a component used in another app that used a component from this UI library that used lodash without importing it 😱 
Closes #435
=> Import lodash at top of all components using it.

package.json, src/SvgIcon/Icons/MapMarker.jsx, src/SvgIcon/SvgIcon.jsx
See screen shot at https://github.com/Thinkful/cuckoo/pull/389
=> Add mapmarker SVG icon

less/modules/app-bar.less, package-lock.json, package.json, src/AppBar/AppBar.jsx, src/AppBar/ConciergeTooltip.jsx, stories/index.stories.js
Point students to new concierge by a tooltip. It doesn't disappear until click the concierge (uses cookie).
=> Add tooltip that calls out concierge

less/modules/app-bar.less, package.json, src/AppBar/AppBar.jsx, src/AppBar/ConciergeTooltip.jsx
Fixes https://phabricator.bloc.io/T12713
The concierge should open if the user clicks on the tip message.
=> T12713 add click event to open concierge when tip clicked

package.json, src/AppBar/AppBar.jsx
Missed a spot where the flag is, and also should bind method to the component...
=> Messed up the release of T13311 -- this gets the flag right.

src/AppBar/AppBar.jsx, src/AppBar/ConciergeModal.jsx
https://phabricator.bloc.io/T13314
=> add configurable open sessions URL option

src/AppBar/AppBar.jsx, src/AppBar/ConciergeModal.jsx
Card: https://phabricator.bloc.io/T13312
=> T13312 Add technical slack link to app bar and concierge modal.

package.json
Releases  changes related to https://phabricator.bloc.io/T13312 and other Prep work.
=> T13312 Bump patch version

package.json, src/AppBar/AppBar.jsx
https://phabricator.bloc.io/T13748
=> roll out concierge to all prep students

src/AppBar/AppBar.jsx
getting an error for this `;` during `npm publish`
=> npm doesnt like ;

less/modules/app-bar.less, package-lock.json, package.json
Card: https://phabricator.bloc.io/T13783
Before:
After:
=> T13783 orange conc note
